config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount YavuSurveys::Engine  => '/surveys',   as: :yavu_surveys if defined?(YavuSurveys::Engine)

  root to: 'dashboard#index'

  get 'dashboard', to: 'dashboard#index'
  get "covers", to: 'covers#index'
  get 'jobs', to: 'dashboard#jobs'
  post 'dashboard/most_box', to: 'dashboard#most_box'

  # API main controller
  get 'api/register', to: 'api#register'
  get 'api/context/:id', to: 'api#context'
  post 'api/accounting', to: 'api#accounting'
  get 'api/:id', to: 'api#show'
  match 'api/service/:id/:component_configuration_id/:service_name', to: 'api#service', via: :all
  match 'api/service/preview/:id/:representation/:route/:component_configuration_id/:service_name', to: 'api#service_preview', via: :all
  post 'api/alive', to: 'api#alive'

  # Serve uploaded component asset content
  get 'component_asset_serve/:id', to: "asset#serve_component_content", as: 'component_asset_serve'

  # Serve uploaded client_application asset content
  get 'client_application_asset_serve/:id', to: "asset#serve_client_application_asset_content", as: 'client_application_asset_serve'

  # Asset Pipeline for frontend preview
  get "#{YavuSettings.assets.prefix}/:identifier/*path",  to: ClientApplicationSprocketsController, via: :all, format: false
  get "#{YavuSettings.assets.prefix_preview}/:identifier/*path",  to: ClientApplicationSprocketsPreviewController, via: :all, format: false

  # Frontend clients management
  get 'frontend_servers', to: "frontend_servers#index"
  post 'frontend_servers/:id/:client_application_id', to: "frontend_servers#configure", as: 'configure_frontend_server'
  put 'frontend_servers/:id', to: "frontend_servers#restart", as: 'restart_frontend_server'

  resources :media do
    collection do
      get 'search'
      get 'autocomplete'
      # Type-specific new object routes
      get 'new_audio'
      get 'new_embedded'
      get 'new_file'
      get 'new_image'
    end

    member do
      get 'find'
    end
  end

  resources :extra_attributes, except: [:show]

  resources :settings, only: [:index] do
    collection do
      get 'edit_all'
      put 'update_all'
    end
  end

  resources :shortcuts, except: [:show, :index] do
    collection do
      get 'manage'
    end

    member do
      put 'remove_from_menu'
      put 'add_to_menu'
    end
  end

  resources :articles do
    member do
      get 'copy'
      get 'media', to: 'articles#media_by_article'
    end

    collection do
      get 'most_commented'
      get 'most_read'
      post 'create_copy'
      get 'search',  as: :search
      get 'search_by_section_and_edition', as: :search_by_section_and_edition
    end
  end

  resources :supplements do
    member do
      post 'become_default'
      get 'sections'
      get 'editions'
      get 'active_edition'
    end
  end

  resources :news_sources do
  end

  resources :sections do
    collection do
      get 'tree'
      get 'search',  as: :search
    end

    member do
      get 'articles'
    end
  end

  resources :tags do
    member do
      get 'combine'
      post 'combine_update'
      post 'blacklist'
      post 'unblacklist'
    end

    collection do
      post 'separate'
      get  'search', as: :search
    end
  end

  resources :editions do
    member do
      put 'become_active'
      get 'articles'
    end

    collection do
      get 'search',  as: :search
    end
  end

  resources :client_applications do
    member do
      get  'preview'
      get  'invalidate_routes'
      get  'extra_attributes'
      get  'update_preview'
      post 'enable'
      post 'disable'
      get  'copy'
      post 'create_copy'
      post 'compile_assets'
      post 'notify_clients'
      post 'invalidate_routes', to: 'client_applications#purge_routes'
      patch 'extra_attributes', to: 'client_applications#manage_extra_attributes'
    end

    collection do
      get 'search',  as: :search
    end

    resources :client_application_assets, as: :assets, path: 'assets' do
      member do
        get 'dissasociate_representations'
        get 'edit_content'
        get 'rename'
        post 'toggle_as'
        patch 'update_name'
        patch 'update_content'
      end
      collection do
        get  'new_empty'
        post 'create_empty'
      end
    end

    resources :routes, as: :routes

    resources :representations, as: :representations do
      member do
        get    'rename'
        get    'cover', to: 'covers#edit'
        patch  'update_cover', to: 'covers#update'
        patch  'update_name'
        get    'copy'
        post   'create_copy'
        delete 'discard_draft'
        get    'preview'
        post   'apply'
        get    'manage_assets'
      end

      resources :base_representations_views, as: :views, path: 'views' do
        member do
          post 'associate'
          post 'disassociate'
        end
      end

      resources :representation_assets, as: :assets, path: 'assets', only: [:index, :show, :edit, :new] do
        collection do
          patch 'batch_action'
          get   'new_empty'
        end
        member do
          get   'rename'
          get   'edit_content'
          post  'toggle_into_representation'
          post  'toggle_as_favicon'
        end
      end

      resources :backups, only: [:index, :show, :destroy] do
        member do
          post 'restore'
        end
      end
    end

    resources :newsletters, as: :newsletters do
      member do
        post 'enable'
        post 'disable'
        get  'sendmail'
      end
    end
  end

  resources :galleries do
    collection do
      get 'new_media'
      get 'search'
    end
  end

  resources :users
  resources :roles
  get 'profile', to: 'users#profile'
  patch 'profile', to: 'users#update_profile'

  resources :components do
    member do
      get  'copy'
      post 'create_copy'
      get  'configuration_form'
      get  'enable'
      get  'disable'
    end

    collection do
      get 'search',  as: :search
    end

    resources :services, controller: 'component_services'

    resources :views, controller: 'component_views' do
      member do
        post :make_default
      end
    end

    resources :component_translations, path: 'translations', as: :translations

    resources :component_assets, as: :assets, path: 'assets' do
      member do
        get 'edit_content'
        get 'rename'
        patch 'update_name'
        patch 'update_content'
      end

      collection do
        get   'new_empty'
        post  'create_empty'
      end
    end
  end

  get 'auditing', to: 'versions#index', as: 'auditing'
  resources :versions, only: [:index, :show, :destroy]
  get 'versions/:id/diff_current', to: 'versions#diff_current', as: 'diff_current'
  post 'versions/:id/restore', to: 'versions#restore', as: 'restore_version'

  # Sidekiq panel
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Debug/Development routes
  if Rails.env.development?
    get 'debug', to: 'debug#index'
    get 'debug/icons', to: 'debug#icons'
  end
end

app/models/concerns/representations/backup_management.rb
module Representations::BackupManagement
  extend ActiveSupport::Concern

  # Return whether this representation has backups
  def has_backups?
    backups.any?
  end

  # Destructively restore the given backup onto this representation.
  # Please note that this representation will be destroyed after this operation.
  # @see Representation#replace_with
  def restore_backup!(backup)
    transaction do
      self.replace_with backup, destroy: true
      client_application.notify_clients
    end
  end
end

app/models/representations/representation_backup.rb
class RepresentationBackup < BaseRepresentation
  belongs_to :representation, foreign_key: 'representation_id', class_name: 'Representation'
  # Validations
  validates :representation, presence: true

  default_scope { order created_at: :desc }

  # Restore this backup, overwriting the associated representation.
  # @see Representation#restore_backup!
  def restore!
    representation.restore_backup! self
  end

  def kind_for_assets
    'backups'
  end
end

app/models/representations/representation_draft.rb
class RepresentationDraft < BaseRepresentation
  belongs_to :representation, foreign_key: 'representation_id'
  # Validations
  validates :representation, presence: true

  # Apply this draft onto its representation
  # @see Representation#apply_draft!
  def apply!
    representation.apply_draft!
  end

  def kind_for_assets
    'drafts'
  end
end

app/controllers/representations_controller.rb
class RepresentationsController < ApplicationController
  load_and_authorize_resource :client_application
  load_and_authorize_resource :representation, through: :client_application
  before_action :order,                       only: [:index]
  before_action :filter,                      only: [:index]
  before_action :clear_filter,                only: [:index]
  before_action :set_representation,          only: [:show, :rename, :update_name, :discard_draft, :destroy]
  before_action :set_original_representation, only: [:edit, :update, :preview, :apply, :manage_assets, :copy, :create_copy]
  before_action :set_representation_draft,    only: [:edit, :update, :preview, :apply, :manage_assets]
  before_action :set_editor_templates,        only: [:edit, :update]
  before_action :ensure_draft_exists,         only: [:edit, :update, :preview, :apply, :manage_assets]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  respond_to :html

  def index
    @representations = @order.sort_list @filter.all.page(params[:page]).per(per_page)
  end

  def show
  end

  def new
    @representation = Representation.new client_application: @client_application
  end

  def rename
  end

  def edit
    @available_components = BaseComponent.available_for_editor
  end

  def copy
    @representation = @original_representation.copy
  end

  def create_copy
    @representation = @original_representation.copy representation_params[:name]
    if @representation.save
      redirect_to client_application_representation_path(@client_application, @representation),
                  notice: I18n.t('representations.copy.messages.success')
    else
      render action: 'copy'
    end
  end

  def create
    @representation = Representation.new(representation_params)
    @representation.client_application = @client_application
    if @representation.save
      redirect_to edit_client_application_representation_path(@client_application, @representation),
                  notice: I18n.t('representations.new.messages.success')
    else
      render action: 'new'
    end
  end

  def update_name
    new_name = params[:representation][:name] rescue nil
    if @representation.update(name: new_name)
      redirect_to client_application_representation_path(@client_application, @representation),
                  notice: I18n.t('representations.update_name.messages.success')
    else
      render action: 'rename'
    end
  end

  def update
    begin
      if @draft.from_json(editor_params[:configuration])
        UniqueAccessWorker.perform_async(view_context.channel_path(@draft, namespace: '/uniqueaccess'), {user: current_user.username, saved: true}, view_context.announcements_url)
        @result = {notice: I18n.t('representations.save_draft.messages.success'), lock_version: BaseRepresentation.find(@draft.id).lock_version}
        @result[:redirect] = preview_path_from(:edit) if editor_params[:operation] == 'apply'
      else
        # Set an error HTTP status code
        self.status = 422
        @result = { alert: I18n.t('representations.apply_draft.messages.fail'), failures: @draft.errors.full_messages }
      end
    rescue ActiveRecord::StaleObjectError
      self.status = 422
      @result = { alert: I18n.t('representations.apply_draft.messages.fail'), failures: [I18n.t('activerecord.errors.stale_object')], lock_version: BaseRepresentation.find(@draft.id).lock_version }
    end

    respond_to do |format|
      format.json do
        render json: @result
      end
      format.html do
        redirect_to edit_client_application_representation_path(@client_application, @draft.representation), @result
      end
    end
  end

  def discard_draft
    old_draft = @representation.draft
    if @representation.discard_draft
      if old_draft
        UniqueAccessWorker.perform_async(view_context.channel_path(old_draft, namespace: '/uniqueaccess'), {user: current_user.username, destroyed: true}, view_context.announcements_url)
      end
      flash[:notice] = I18n.t('representations.discard_draft.messages.success')
    else
      flash[:alert] = I18n.t('representations.discard_draft.messages.failed')
    end
    redirect_to params[:gbt] || client_application_representations_path(@client_application)
  end

  def destroy
    if @representation.destroy
      if @representation.has_draft?
        UniqueAccessWorker.perform_async(view_context.channel_path(@representation.draft, namespace: '/uniqueaccess'), {user: current_user.username, destroyed: true}, view_context.announcements_url)
      end
      flash[:notice] = I18n.t('representations.destroy.messages.success')
    else
      flash[:alert] = I18n.t('representations.destroy.messages.error')
    end
    redirect_to client_application_representations_path(@client_application)
  end

  def preview
    @go_back = params[:gbt] || client_application_representations_path(@client_application)
    @default_route = @client_application.routes.find_by representation: @original_representation
    render 'client_applications/preview', layout: 'preview'
  end

  def apply
    @draft.apply!
    # At this point, THE representation is the previous draft
    @representation = @draft
    # Send to purge the representation's routes
    Purger.purge_representation @representation
    UniqueAccessWorker.perform_async(view_context.channel_path(@draft, namespace: '/uniqueaccess'), {user: current_user.username, destroyed: true}, view_context.announcements_url)
    redirect_to params[:gbt] || client_application_representations_path(@client_application),
                notice: I18n.t('representations.apply_draft.messages.success')
  end

  def manage_assets
    redirect_to client_application_representation_assets_path(@client_application, @draft)
  end

  private

  def record_not_found
    redirect_to client_applications_path, alert: I18n.t('representations.errors.invalid_client_application_or_representation')
  end

  # Return the requested representation from those belonging to @client_application.
  # Redirect to +client_application_representations_path+ if unable to find the representation.
  def fetch_representation
    @client_application.representations.find(params[:id])
  end

  # Set the requested representation in @representation.
  # @see RepresentationsController#fetch_representation
  def set_representation
    @representation = fetch_representation
  end

  # Set the requested representation in @original_representation.
  # @see RepresentationsController#fetch_representation
  def set_original_representation
    @original_representation = fetch_representation
  end

  # Set the requested draft in @draft and @representation.
  # @see RepresentationsController#fetch_representation
  def set_representation_draft
    @representation = @draft = @original_representation.draft.tap do |draft|
      if draft
        draft.enable_locking!
        draft.lock_version = lock_version_params[:representation][:lock_version] if lock_version_params[:representation] && lock_version_params[:representation][:lock_version]
      end
    end
  end

  def set_editor_templates
    @row_template = Row.new
    @column_template = Column.new
    @component_configuration_template = ComponentConfiguration.new description: I18n.t('representations.edit.component.default_description'), component: Component.new
  end

  def representation_params
    params.require(:representation).permit(:name, :configuration)
  end

  def editor_params
    params.require(:representation).permit(:configuration, :operation)
  end

  def cover_params
    params.require(:cover).permit(:configuration, :operation)
  end

  def lock_version_params
    params.permit(representation: [:lock_version])
  end

  def ensure_draft_exists
    unless @draft.present?
      @original_representation.trigger_draft_creation
      redirect_to client_application_representations_path(@client_application),
                  alert: I18n.t('representations.errors.draft_unavailable')
    end
  end

  def order
    @order = create_order RepresentationsOrder, sort: sort_params
  end

  def filter_params
    if params.has_key?(:filter)
      params.require(:filter).permit(:name).to_options
    end
  end

  # Create the @filter object with the currently-set values for the filters
  def filter
    @filter = create_filter RepresentationsFilter, {values: filter_params}
    @filter.client_application = @client_application
    @filter
  end

  # Clear the currently-set filters, restoring them to the defaults
  def clear_filter
    if params[:commit] == t('activerecord.actions.shared.clear_filter')
      @filter.clear!
      redirect_to request.path
    end
  end

  def preview_path_from(action)
    path = send(:"#{action}_client_application_representation_path", @client_application, @original_representation)
    preview_client_application_representation_path(@client_application, @original_representation, gbt: path)
  end
end

app/views/representations/_actions_dropdown.html.erb
<%= render_dropdown_actions(representation, :representation,
  {
    show:   { url: client_application_representation_path(@client_application, representation) },
    rename: { url: rename_client_application_representation_path(@client_application, representation) },
    draft_preview_and_publish:
    {
      url: preview_client_application_representation_path(@client_application, representation, gbt: client_application_representations_path(@client_application)),
      condition: representation.has_draft?
    },
    disabled: 
    {
      disable_text: t('activerecord.actions.representation.draft_preview_and_publish'),
      condition: !representation.has_draft?,
      disabled: true
    },
    desing:   
    {
      title: true,
      text: t('activerecord.actions.representation.groups.design'),
      divider: true
    },
    assets: { url: manage_assets_client_application_representation_path(@client_application, representation) },
    edit:   { url: edit_client_application_representation_path(@client_application, representation) },
    copy:   
    { 
      url: copy_client_application_representation_path(@client_application, representation),
      class: 'success'
    },
    alternative_views: { url: client_application_representation_views_path(@client_application, representation) },
    editorial:
    {
      title: true,
      text: t('activerecord.actions.representation.groups.editorial'),
      divider: true
    },
    discard_draft:
    { 
      url: discard_draft_client_application_representation_path(@client_application, representation), 
      method: :delete, 
      data: { confirm: t('representations.actions.confirmation.discard_draft') },
      condition: representation.has_draft?
    },
    disble_discard_draft:
    {
      disable_text: t('activerecord.actions.representation.discard_draft'),
      condition: !representation.has_draft?,
      disabled: true
    },
    destroy: { url: client_application_representation_path(@client_application, representation) }
  }
) %>

app/views/representations/_filter.html.erb
<div class="filter-form-container" <%= plugins collapsible: { useToggle: '#filters-toggle', labels: { rise: t('activerecord.actions.shared.show_filter'), collapse: t('activerecord.actions.shared.hide_filter') }, collapseOnInit: !@filter.any? } %>>
  <%= form_tag '', :class => 'filters-form', :method => :get do %>
    <div class="field-container">
      <section class="section active">
        <div class="content">
          <div class="row">
            <div class="large-3 columns">
              <%= label :filter, :name, t('activerecord.attributes.representation.name'), class: 'inline right' %>
            </div>
            <div class="large-9 columns">
              <%= text_field :filter, :name %>
            </div>
          </div>
        </div>
      </section>
    </div>

    <div class="row">
      <div class="large-10 columns large-offset-2">
        <%= submit_tag t('activerecord.actions.shared.filter'), class: 'button radius small' %>
        <%= submit_tag t('activerecord.actions.shared.clear_filter'), class: 'button radius secondary small' %>
      </div>
    </div>
  <% end %>
</div>

app/views/representations/_form.html.erb
<div class="form-container">
  <%= form_for [@client_application, @representation], url: url do |f| %>
    <%= render_form_errors @representation  %>

    <div class="field-container panel">
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
    </div>

    <ul class="form-actions right">
      <li><%= f.submit class: 'action button radius success' %></li>
    </ul>
  <% end %>
</div>

app/views/representations/copy.html.erb
<div class="crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li><%= link_to t('representations.label.plural'), client_application_representations_path(@client_application) %></li>
    <li>&nbsp;</li>
  </ul>

  <h1><%= title t('representations.copy.title') %></h1>
  <h2><%= t('representations.copy.original_representation', representation: @original_representation) %></h2>
</div>

<%= render_flashes %>

<%= render 'form', url: create_copy_client_application_representation_path(@client_application, @original_representation) %>

<%= render_context_actions :representation, left: { back: { url: client_application_representations_path(@client_application) } } %>

app/views/representations/edit.html.erb
<div class="crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li><%= link_to t('representations.label.plural'), client_application_representations_path(@client_application) %></li>
    <li><%= link_to @draft.name, client_application_representation_path(@client_application, @draft.representation) %></li>
    <li>&nbsp;</li>
  </ul>

  <h1><%= title t('representations.edit.title') %></h1>

  <%= render_flashes %>
</div>

<div class="editor-container"
     <%= plugins 'representationeditor' => { componentFormUrl: configuration_form_component_path(':id') },
                 'uniqueaccess' => {url: announcements_url, channel: channel_path(@draft, namespace: '/uniqueaccess'), user: current_user.username,
                                    legend: t('representations.edit.unique_access.legend'),
                                    changedText: t('representations.edit.unique_access.made_changes'),
                                    savedText: t('representations.edit.unique_access.saved'),
                                    destroyedText: t('representations.edit.unique_access.destroyed')} %>
>
  <div class="show-on-load fade-in hideable-editor">
    <%= render partial: 'representations/representation_editor/editor' %>
  </div>

  <div class="loader show-while-loading">
    <p><%= image_tag 'indicator-large.gif' %></p>
    <p><%= t 'representations.edit.loading' %></p>
  </div>

  <%= form_for [@client_application, @draft.representation], id: 'draft_form', url: client_application_representation_path(@client_application, @draft.representation) do |f| %>
    <%= f.hidden_field :configuration, value: '', id: 'representation_configuration' %>
    <%= f.hidden_field :operation, value: '', id: 'representation_operation' %>
    <%= f.hidden_field :lock_version, value: @draft.lock_version %>

    <ul class="form-actions right show-on-load no-js-hidden fade-in">
      <li>
        <%= f.submit t('representations.actions.save_draft'), name: 'save', id: 'save-draft', class: 'action button radius' %>
      </li>
      <li>
        <%= f.submit t('representations.edit.actions.apply_draft.regular'),
                     name: 'apply',
                     id: 'apply-draft',
                     class: 'action button radius success tip-top',
                     title: t('representations.edit.notices.apply_draft'),
                     data: { regular_text: t('representations.edit.actions.apply_draft.regular'),
                             submission_text: t('representations.edit.actions.apply_draft.processing'),
                             success_text: t('representations.edit.actions.apply_draft.success'),
                             error_text: t('representations.edit.actions.apply_draft.error'),
                             tooltip: true } %>
      </li>
    </ul>
  <% end %>
</div>

<%= render_context_actions :representation, left: { back: { url: client_application_representations_path(@client_application) } } %>

app/views/representations/index.html.erb
<div class="row crud-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li>&nbsp;</li>
  </ul>
  <div class="row">
    <h1 class="large-7 columns">
      <%= title t('representations.list.title') %>
    </h1>

    <div class="large-5 columns quick-filter-container">
      <%= render_simple_filter(client_application_representations_path(@client_application), :name) %>
    </div>
  </div>
</div>

<%= render_flashes %>

<%= render_context_actions :representation, right: { new: { url: new_client_application_representation_path } }, target: Representation %>

<p><%= kaminari_info @representations %></p>

<table class="crud-table">
  <thead>
  <tr>
    <th class="large-4">
      <%= render partial: 'shared/sort_field_link' , locals: {list_name: 'representations', field: 'name', label: t('activerecord.attributes.representation.name').capitalize } %>
    </th>
    <th class="large-3"><%= t('representations.list.backups') %></th>
    <th class="large-3"><%= t('representations.list.routes') %></th>
    <th class="large-2"></th>
  </tr>
  </thead>

  <tbody>
  <% @representations.each do |representation| %>
    <tr>
      <td><%= representation.name %></td>
      <td><%= render_value representation.backups.count %></td>
      <td>
        <%= render_value render_collection representation.routes %>
      </td>
      <td><%= render partial: 'actions_dropdown', locals: { representation: representation } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="row crud-footer">
  <div class="large-4 columns">
    <%= render 'shared/pagination_resizer' %>
  </div>

  <div class="large-8 columns">
    <%= paginate @representations %>
  </div>
</div>

<%= render_context_actions :client_application, left: { back: {url: client_applications_path} } %>

app/views/representations/new.html.erb
<div class="crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li><%= link_to t('representations.label.plural'), client_application_representations_path(@client_application) %></li>
    <li>&nbsp;</li>
  </ul>

  <h1><%= title t('representations.new.title') %></h1>
</div>

<%= render_flashes %>

<%= render 'form', url: client_application_representations_path(@client_application, @representation) %>

<%= render_context_actions :representation, left: { back: { url: client_application_representations_path(@client_application) } } %>

app/views/representations/rename.html.erb
<div class="crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li><%= link_to t('representations.label.plural'), client_application_representations_path(@client_application) %></li>
    <li>&nbsp;</li>
  </ul>

  <h1><%= title t('representations.rename.title') %></h1>
</div>

<%= render_flashes %>

<%= render 'form', url: update_name_client_application_representation_path(@client_application, @representation), method: :patch %>

<%= render_context_actions :representation, left: { back: { url: client_application_representations_path(@client_application) } } %>

app/views/representations/show.html.erb
<div class="crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application, client_application_path(@client_application) %></li>
    <li><%= link_to t('representations.label.plural'), client_application_representations_path(@client_application) %></li>
    <li>&nbsp;</li>
  </ul>

  <h1><%= title t('representations.show.title') %></h1>
</div>

<%= render_flashes %>

<div class="panel show-field-container">
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.representation.client_application' %></div>
    <div class="large-9 columns"><%= render_value @representation.client_application %></div>
  </div>
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.representation.name' %></div>
    <div class="large-9 columns"><%= render_value @representation.name %></div>
  </div>

  <% if @representation.has_draft? %>
    <fieldset>
      <legend><%= t 'activerecord.attributes.representation.draft' %></legend>

      <div class="row">
        <div class="large-3 columns label-element"><%= t 'activerecord.attributes.draft.created_at' %></div>
        <div class="large-9 columns"><%= l @representation.draft.created_at %></div>
      </div>
    </fieldset>
  <% else %>
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.representation.draft' %></div>
    <div class="large-9 columns n-a"><%= t 'activerecord.attributes.representation.no_draft' %></div>
  </div>
  <% end %>

  <% if @representation.has_backups? %>
    <fieldset>
      <legend><%= t 'activerecord.attributes.representation.backups' %></legend>

      <% @representation.backups.each do |backup| %>
        <div class="row">
          <div class="large-3 columns label-element"><%= t 'activerecord.attributes.backups.created_at' %></div>
          <div class="large-9 columns">
            <%= link_to l(backup.created_at, format: :long_with_time), client_application_representation_backup_path(@client_application, @representation, backup) %>
          </div>
        </div>
      <% end %>
    </fieldset>
  <% else %>
    <div class="row">
      <div class="large-3 columns label-element"><%= t 'activerecord.attributes.representation.backups' %></div>
      <div class="large-9 columns n-a"><%= t 'activerecord.attributes.representation.no_backups' %></div>
    </div>
  <% end %>

  <!-- TODO: Include information about where this representation is being used -->
</div>

<%= render partial: 'paper_trail/versions/versions', locals: {versions: @representation.versions} %>

<%= render_context_actions :representation,
  left: {
    back: { url: client_application_representations_path(@client_application) }
  },
  right: {
    edit: { url: edit_client_application_representation_path(@client_application, @representation) }
  },
  target: @representation %>