config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount YavuSurveys::Engine  => '/surveys',   as: :yavu_surveys if defined?(YavuSurveys::Engine)

  root to: 'dashboard#index'

  get 'dashboard', to: 'dashboard#index'
  get "covers", to: 'covers#index'
  get 'jobs', to: 'dashboard#jobs'
  post 'dashboard/most_box', to: 'dashboard#most_box'

  # API main controller
  get 'api/register', to: 'api#register'
  get 'api/context/:id', to: 'api#context'
  post 'api/accounting', to: 'api#accounting'
  get 'api/:id', to: 'api#show'
  match 'api/service/:id/:component_configuration_id/:service_name', to: 'api#service', via: :all
  match 'api/service/preview/:id/:representation/:route/:component_configuration_id/:service_name', to: 'api#service_preview', via: :all
  post 'api/alive', to: 'api#alive'

  # Serve uploaded component asset content
  get 'component_asset_serve/:id', to: "asset#serve_component_content", as: 'component_asset_serve'

  # Serve uploaded client_application asset content
  get 'client_application_asset_serve/:id', to: "asset#serve_client_application_asset_content", as: 'client_application_asset_serve'

  # Asset Pipeline for frontend preview
  get "#{YavuSettings.assets.prefix}/:identifier/*path",  to: ClientApplicationSprocketsController, via: :all, format: false
  get "#{YavuSettings.assets.prefix_preview}/:identifier/*path",  to: ClientApplicationSprocketsPreviewController, via: :all, format: false

  # Frontend clients management
  get 'frontend_servers', to: "frontend_servers#index"
  post 'frontend_servers/:id/:client_application_id', to: "frontend_servers#configure", as: 'configure_frontend_server'
  put 'frontend_servers/:id', to: "frontend_servers#restart", as: 'restart_frontend_server'

  resources :media do
    collection do
      get 'search'
      get 'autocomplete'
      # Type-specific new object routes
      get 'new_audio'
      get 'new_embedded'
      get 'new_file'
      get 'new_image'
    end

    member do
      get 'find'
    end
  end

  resources :extra_attributes, except: [:show]

  resources :settings, only: [:index] do
    collection do
      get 'edit_all'
      put 'update_all'
    end
  end

  resources :shortcuts, except: [:show, :index] do
    collection do
      get 'manage'
    end

    member do
      put 'remove_from_menu'
      put 'add_to_menu'
    end
  end

  resources :articles do
    member do
      get 'copy'
      get 'media', to: 'articles#media_by_article'
    end

    collection do
      get 'most_commented'
      get 'most_read'
      post 'create_copy'
      get 'search',  as: :search
      get 'search_by_section_and_edition', as: :search_by_section_and_edition
    end
  end

  resources :supplements do
    member do
      post 'become_default'
      get 'sections'
      get 'editions'
      get 'active_edition'
    end
  end

  resources :news_sources do
  end

  resources :sections do
    collection do
      get 'tree'
      get 'search',  as: :search
    end

    member do
      get 'articles'
    end
  end

  resources :tags do
    member do
      get 'combine'
      post 'combine_update'
      post 'blacklist'
      post 'unblacklist'
    end

    collection do
      post 'separate'
      get  'search', as: :search
    end
  end

  resources :editions do
    member do
      put 'become_active'
      get 'articles'
    end

    collection do
      get 'search',  as: :search
    end
  end

  resources :client_applications do
    member do
      get  'preview'
      get  'invalidate_routes'
      get  'extra_attributes'
      get  'update_preview'
      post 'enable'
      post 'disable'
      get  'copy'
      post 'create_copy'
      post 'compile_assets'
      post 'notify_clients'
      post 'invalidate_routes', to: 'client_applications#purge_routes'
      patch 'extra_attributes', to: 'client_applications#manage_extra_attributes'
    end

    collection do
      get 'search',  as: :search
    end

    resources :client_application_assets, as: :assets, path: 'assets' do
      member do
        get 'dissasociate_representations'
        get 'edit_content'
        get 'rename'
        post 'toggle_as'
        patch 'update_name'
        patch 'update_content'
      end
      collection do
        get  'new_empty'
        post 'create_empty'
      end
    end

    resources :routes, as: :routes

    resources :representations, as: :representations do
      member do
        get    'rename'
        get    'cover', to: 'covers#edit'
        patch  'update_cover', to: 'covers#update'
        patch  'update_name'
        get    'copy'
        post   'create_copy'
        delete 'discard_draft'
        get    'preview'
        post   'apply'
        get    'manage_assets'
      end

      resources :base_representations_views, as: :views, path: 'views' do
        member do
          post 'associate'
          post 'disassociate'
        end
      end

      resources :representation_assets, as: :assets, path: 'assets', only: [:index, :show, :edit, :new] do
        collection do
          patch 'batch_action'
          get   'new_empty'
        end
        member do
          get   'rename'
          get   'edit_content'
          post  'toggle_into_representation'
          post  'toggle_as_favicon'
        end
      end

      resources :backups, only: [:index, :show, :destroy] do
        member do
          post 'restore'
        end
      end
    end

    resources :newsletters, as: :newsletters do
      member do
        post 'enable'
        post 'disable'
        get  'sendmail'
      end
    end
  end

  resources :galleries do
    collection do
      get 'new_media'
      get 'search'
    end
  end

  resources :users
  resources :roles
  get 'profile', to: 'users#profile'
  patch 'profile', to: 'users#update_profile'

  resources :components do
    member do
      get  'copy'
      post 'create_copy'
      get  'configuration_form'
      get  'enable'
      get  'disable'
    end

    collection do
      get 'search',  as: :search
    end

    resources :services, controller: 'component_services'

    resources :views, controller: 'component_views' do
      member do
        post :make_default
      end
    end

    resources :component_translations, path: 'translations', as: :translations

    resources :component_assets, as: :assets, path: 'assets' do
      member do
        get 'edit_content'
        get 'rename'
        patch 'update_name'
        patch 'update_content'
      end

      collection do
        get   'new_empty'
        post  'create_empty'
      end
    end
  end

  get 'auditing', to: 'versions#index', as: 'auditing'
  resources :versions, only: [:index, :show, :destroy]
  get 'versions/:id/diff_current', to: 'versions#diff_current', as: 'diff_current'
  post 'versions/:id/restore', to: 'versions#restore', as: 'restore_version'

  # Sidekiq panel
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Debug/Development routes
  if Rails.env.development?
    get 'debug', to: 'debug#index'
    get 'debug/icons', to: 'debug#icons'
  end
end

app/models/tag.rb
# Documentation for Tag class
#
# == Summary
#
# An instance of this class is created with:
# * name
# * slug
#
# == Example
#
# tag = Tag.create(:tag, name:'aName')
#
# === Class Tag
#
#
class Tag < ActiveRecord::Base
  MAX_SLUG_LENGTH = 240
  MINIMUM_NAME_LENGTH = 3

  include Versionable

  # Associations
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :media
  belongs_to              :combiner, class_name: 'Tag'
  has_many                :combined, class_name: 'Tag',
                                     foreign_key: 'combiner_id',
                                     dependent: :destroy
  has_many                :sections, through: :articles
  # Callbacks
  before_create :set_slug
  after_create :set_slug_postfix
  before_validation :squish_name
  # Validations
  validates :name, presence: true, length: { minimum: MINIMUM_NAME_LENGTH, maximum: 255 }, uniqueness: true
  validates :slug, uniqueness: true
  # Scopes
  # 'relation' can be :articles or :media
  scope :not_used_in, -> (relation) { includes(relation).where(relation => { id: nil }) }
  scope :used_in,     -> (relation) { eager_load(relation).where.not(relation => { id: nil }) }
  scope :not_used,    -> { where(id: not_used_in(:articles) & not_used_in(:media)) }
  scope :used,        -> { where(id: used_in(:articles) + used_in(:media)) }
  scope :root,        -> { where(combiner_id: nil) }
  scope :visible,     -> { root.where(hidden: false) }
  scope :hidden,      -> { where(hidden: true) }
  default_scope { order(:name) }

  set_api_resource id: :slug,
    name: :name

  def used?
    articles.any? || media.any?
  end

  def unused?
    !used?
  end

  # Returns all tags least sent as parameter.
  def self.but(*tags)
    where.not(id: tags)
  end

  # Returns a collection of tags that meet the parameter comparing name
  # with like if no parameter is passed all tags are returned.
  def self.search(params = {})
    scope = all
    scope = scope.where('name like :query', query: "%#{params[:query]}%") unless params[:query].blank?
    scope = scope.but(params[:except]) unless params[:except].blank?
    scope
  end

  # Return a comma-delimited string with the NAMEs of the combined tags
  # associated to this tag
  def serialized_combined
    combined.collect(&:name).join(',')
  end

  # Add tags to set tags combined with this, and tells each of
  # the new combined update their references via #combined_with!
  def combines!(tags)
    combined << tags

    tags = [tags] unless tags.respond_to? :each
    tags.each { |tag| tag.combine_with! self }
  end

  # Returns the name after apply the squish method if name is not nil,
  # name.squish =>
  #   First removing all whitespace on both ends of the string,
  #   and then changing remaining consecutive whitespace groups into one space each.
  def squish_name
    self.name = name.squish if name
  end

  # Update all references to this tag so that they now point at :other_tag.
  def combine_with!(other_tag)
    other_tag.combines! combined unless combined.empty?

    other_tag.articles << articles.where.not(id: other_tag.articles)
    articles.clear
  end

  # Isolated this tag and persists
  def separate!
    self.combiner = nil
    save
  end

  def to_s
    name.to_s
  end

  # Detects tags whose name is similar to the name of this label
  # The delta indicates how many characters from the end of this
  # Name of the label can be removed to search for other labels
  # Similar names.
  #
  # Example::
  #    tag = Tag.find(9)
  #    tag.name
  #      # => 'Educational'
  #    tag.similar 5
  #      # => ['Eductionality, Education']
  def similar(delta = 3)
    search = name[0..-delta]
    Tag.visible.where('name like ?', "%#{search}%").but(self)
  end

  protected

  # Before-create callback that generates a slug for this tag if
  # none has been defined yet. The slug will be truncated to a maximum of
  # Tag::MAX_SLUG_LENGTH characters
  def set_slug
    self.slug = name.parameterize if slug.blank?
    self.slug = slug.truncate(MAX_SLUG_LENGTH, omission: '', separator: '-') if slug.length > MAX_SLUG_LENGTH
  end

  # After the tag is created and you can get the id of the same,
  # it concatenates the slug
  def set_slug_postfix
    slug << "-#{id}"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource

  before_action :order, only: [:index]
  before_action :filter, only: [:index]
  before_action :clear_filter, only: [:index]

  def index
    @in_scope = params['hidden'].present? ? :hidden : :visible
    @tags = @order.sort_list @filter.all(@in_scope).page(params[:page]).per(per_page)
  end

  def show
  end

  def new
  end

  def edit
  end

  def combine
  end

  def combine_update
    tags = Tag.where(name: serialized_combined_param)
    @tag.combines! tags
    redirect_to tag_path(@tag), notice: t('tags.combine.messages.success')
  end

  def separate
    @tag = Tag.find_by!(id: params[:id])
    @tag.separate!
    render nothing: true
  end

  def create
    if @tag.save
      redirect_to @tag, notice: t('tags.new.messages.success')
    else
      render action: 'new'
    end
  end

  def search
    ids = (params[:ids] || []).reject(&:blank?)

    if ids.empty?
      matches = Tag.search({ query: params[:q], except: params[:except]}).limit(search_limit)
    else
      matches = Tag.where(name: ids)
    end

    key_method = params[:key_method].presence || :name
    result = matches.map do |tag|
      {id: tag.send(key_method), text: tag.to_s}
    end

    render json: result
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: t('tags.edit.messages.success')
    else
      render action: 'edit'
    end
  end

  def destroy
    if @tag.destroy
      flash[:notice] = I18n.t('tags.destroy.messages.success')
    else
      flash[:alert] = I18n.t('tags.destroy.messages.error')
    end
    redirect_to tags_path(page: current_page)
  end

  def unblacklist
    status = (@tag.update(hidden: false) ? 'notice' : 'error')
    flash[status.to_sym] = I18n.t("tags.unblacklist.message.#{status}", tag: @tag)
    redirect_to "#{tags_path(hidden: true, page: params[:page])}#tag_#{params[:nt]}"
  end

  def blacklist
    status = (@tag.update(hidden: true) ? 'notice' : 'error')
    flash[status.to_sym] = I18n.t("tags.blacklist.message.#{status}", tag: @tag)
    redirect_to "#{tags_path(page: params[:page])}#tag_#{params[:nt]}"
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :slug, :combined, :serialized_combined, :hidden)
  end

  def filter_params
    if params.has_key?(:filter)
      params.require(:filter).permit(:name).to_options
    end
  end

  def filter
    @filter = create_filter TagsFilter, values: filter_params
  end

  def order
    @order = create_order TagsOrder, {sort: sort_params}
  end

  def clear_filter
    if params[:commit] == t('activerecord.actions.shared.clear_filter')
      @filter.clear!

      redirect_to request.path
    end
  end

  def serialized_combined_param
    tag_params[:serialized_combined].split(',').reject(&:blank?)
  end
end

app/views/tags/_combine_form.html.erb
<%= form_for(@tag, url: combine_update_tag_path(@tag), method: :post) do |f| %>
  <div class="field-container panel">
    <div class="row">
      <p class="large-12 columns hint"><%= raw t('tags.combine.description', tag: @tag) %></p>
    </div>
    <div class="row">
      <div class="field large-6 columns">
        <%= f.label :name %>
        <strong class="n-a"><%= render_value raw @tag.name %></strong>
      </div>
      <div class="field large-6 columns">
        <%= f.label :slug %>
        <p class="n-a"><%= render_value raw @tag.slug %></p>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <fieldset id="already-combined">
          <legend><%= t('tags.combine.already_combined', tag: @tag) %></legend>

          <div class="row">
            <% if @tag.combined.any? %>
              <p class="large-12 columns hint">
                <%= t('tags.combine.already_combined_description', separate: t('tags.combine.separate')) %>
              </p>

              <% @tag.combined.each do |tag| %>
                <div class="large-12 columns already-combined-item">
                  <span class="large-1 columns">
                    <a href="#" class="button radius tiny alert separate-button" data-id="<%= tag.id %>" data-name="<%= tag %>">
                      <%= t('tags.combine.separate') %>
                    </a>
                  </span>
                  <p class="large-11 columns"><%= tag %></p>
                </div>
              <% end %>
            <% else %>
              <div class="large-12 columns n-a"><%= t('tags.combine.nothing') %></div>
            <% end %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <fieldset id="similar">
          <legend><%= t('tags.combine.similar') %></legend>

          <div class="row">
            <% if @tag.similar(@tag.name.length / 4).any? %>
              <p class="large-12 columns hint">
                <%= t('tags.combine.similar_description', include: t('tags.combine.include')) %>
              </p>

              <% @tag.similar.each do |tag| %>
                <div class="large-12 columns similar-item">
                  <span class="large-2 columns">
                    <a href="#" class="button tiny radius success combine-button" data-id="<%= tag.id %>">
                      <%= t('tags.combine.include') %>
                    </a>
                  </span>
                  <p class="large-10 columns"><%= tag %></p>
                </div>
              <% end %>
            <% else %>
              <div class="large-12 columns n-a"><%= t('tags.combine.nothing') %></div>
            <% end %>
          </div>
        </fieldset>
      </div>
      <div class="large-6 columns">
        <fieldset>
          <legend><%= t('tags.combine.specific') %></legend>

          <div class="row">
            <p class="large-12 columns hint">
              <%= t('tags.combine.specific_description') %>
            </p>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <%= f.label :serialized_combined, t('tags.combine.available') %>
              <%= ajax_select2_field :tag, :serialized_combined, search_tags_path(except: @tag), { escape_markup: false }, { prompt: true, multiple: true, placeholder: t('tags.combine.select_tags') } %>
            </div>
          </div>
        </fieldset>
      </div>
    </div>
  </div>

  <ul class="form-actions right">
    <li><%= f.submit value: t('tags.combine.submit'), class: 'action button radius success' %></li>
  </ul>
<% end %>

app/views/tags/_filter.html.erb
<div class="filter-form-container" <%= plugins collapsible: { useToggle: '#filters-toggle', labels: { rise: t('activerecord.actions.shared.show_filter'), collapse: t('activerecord.actions.shared.hide_filter') }, collapseOnInit: !@filter.any? } %>>
  <%= form_tag(tags_path, :class => 'filters-form', method: :get) do %>
    <div class="field-container">
      <div class="row">
        <div class="large-2 columns">
          <%= label :filter, :name, t('activerecord.attributes.tag.name'), class: 'right inline' %>
        </div>
        <div class="large-10 columns">
          <%= text_field :filter, :name, class: 'six' %>
        </div>
      </div>
      <ul class="form-actions large-10 columns large-offset-2">
        <li><%= submit_tag t('activerecord.actions.shared.filter'), class: 'button radius small' %></li>
        <li><%= submit_tag t('activerecord.actions.shared.clear_filter'), class: 'button radius small secondary' %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/tags/_form.html.erb
<div class="form-container">
  <%= form_for(@tag) do |f| %>

    <%= render_form_errors @tag  %>

    <div class="field-container panel">
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :slug %>
          <%= f.text_field :slug %>
          <span class='hint'><%= t('tags.new.slug_advice') %></span>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :hidden do -%>
            <%= f.check_box :hidden %>
            <%= t('activerecord.attributes.tag.hidden') %>
          <% end -%>
          <span class="hint"><%= t('activerecord.attributes.tag.hidden_hint') %></span>
        </div>
      </div>
    </div>

    <ul class="form-actions right">
      <li><%= f.submit class: "action button radius success" %></li>
    </ul>
  <% end %>
</div>

app/views/tags/_tag_visibility_switcher.html.erb
<% if @in_scope == :visible %>
  <p><%= link_to t('tags.list.show_hidden'), tags_path(hidden: true) %></p>
<% else %>
  <p><%= link_to t('tags.list.show_unhidden'), tags_path %></p>
<% end %>

app/views/tags/combine.html.erb
<h1><%= title t('tags.combine.title', tag: @tag) %></h1>

<%= render_flashes %>

<div class="form-container" <%= plugins combinetags: { separateEndpoint: separate_tags_path, separateConfirmation: t('tags.combine.separateConfirmation') } %>>
  <%= render 'combine_form' %>
</div>

<%= render_context_actions :tag, right: { back: { url: tags_path } } %>

app/views/tags/edit.html.erb
<h1><%= title t('tags.edit.title') %></h1>

<%= render_flashes %>

<%= render 'form' %>

<%= render_context_actions :tag, left: {
  back: { url: tags_path },
  show: { url: @tag }
} %>

app/views/tags/index.html.erb
<div class="row crud-header">
  <h1 class="large-6 columns">
    <%= title @in_scope == :visible ? t('tags.list.title') : t('tags.list.hidden_title') %>
  </h1>

  <div class="large-6 columns quick-filter-container">
    <%= render_simple_filter(tags_path, :name) %>
  </div>
</div>

<%= render_flashes %>

<%= render_context_actions :tag, right: { new: { url: new_tag_path } }, target: Tag %>

<p><%= kaminari_info @tags %></p>

<%= render partial: 'tag_visibility_switcher' %>

<table class="crud-table">
  <thead>
    <tr>
      <th class="large-5">
        <%= render partial: 'shared/sort_field_link' , locals: {list_name: 'tags', field: 'name', label: t('activerecord.attributes.tag.name') } %>
      </th>
      <th class="large-5">
        <%= render partial: 'shared/sort_field_link' , locals: {list_name: 'tags', field: 'slug', label: t('activerecord.attributes.tag.slug') } %>
      </th>
      <th class="large-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each.with_index do |tag, i| %>
      <tr id="tag_<%= tag.id %>">
        <td><%= raw tag.name %></td>
        <td><%= raw tag.slug %></td>
        <td>
          <%= render_dropdown_actions tag, :tag, show:        {url: tag_path(tag)},
                                                 edit:        {url: edit_tag_path(tag)},
                                                 combine:     {url: combine_tag_path(tag)},
                                                 blacklist:   {url: blacklist_tag_path(tag, page: params[:page], nt: @tags[i+1]), method: :post, condition: !tag.hidden?},
                                                 unblacklist: {url: unblacklist_tag_path(tag, page: params[:page], nt: @tags[i+1]), method: :post, condition: tag.hidden?},
                                                 destroy:     {url: tag_path(tag)} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row crud-footer">
  <div class="large-4 columns">
    <%= render 'shared/pagination_resizer' %>
  </div>

  <div class="large-8 columns">
    <%= paginate @tags %>
  </div>
</div>

app/views/tags/new.html.erb
<h1><%= title t('tags.new.title') %></h1>

<%= render_flashes %>

<%= render 'form' %>

<%= render_context_actions :tag, left: { back: { url: tags_path } } %>

app/views/tags/show.html.erb
<h1><%= title t('tags.show.title') %></h1>

<%= render_flashes %>

<div class="panel show-field-container">
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.tag.name' %></div>
    <div class="large-9 columns"><%= render_value raw @tag.name %></div>
  </div>

  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.tag.slug' %></div>
    <div class="large-9 columns"><%= render_value raw @tag.slug %></div>
  </div>

  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.tag.combined' %></div>
    <div class="large-9 columns"><%= render_value @tag.combined.join(', ') %></div>
  </div>

  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.tag.hidden' %></div>
    <div class="large-9 columns"><%= render_boolean @tag.hidden %></div>
  </div>
</div>

<%= render partial: 'paper_trail/versions/versions', locals: {versions: @tag.versions} %>

<%= render_context_actions :tag, left: { back: {url: tags_path} },
                                 right: { combine: {url: combine_tag_path(@tag), text: t('tags.combine.title', tag: @tag)},
                                          edit:    {url: edit_tag_path(@tag)},
                                          destroy: {url: tag_path(@tag)} },
                                 target: @tag %>