config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount YavuSurveys::Engine  => '/surveys',   as: :yavu_surveys if defined?(YavuSurveys::Engine)

  root to: 'dashboard#index'

  get 'dashboard', to: 'dashboard#index'
  get "covers", to: 'covers#index'
  get 'jobs', to: 'dashboard#jobs'
  post 'dashboard/most_box', to: 'dashboard#most_box'

  # API main controller
  get 'api/register', to: 'api#register'
  get 'api/context/:id', to: 'api#context'
  post 'api/accounting', to: 'api#accounting'
  get 'api/:id', to: 'api#show'
  match 'api/service/:id/:component_configuration_id/:service_name', to: 'api#service', via: :all
  match 'api/service/preview/:id/:representation/:route/:component_configuration_id/:service_name', to: 'api#service_preview', via: :all
  post 'api/alive', to: 'api#alive'

  # Serve uploaded component asset content
  get 'component_asset_serve/:id', to: "asset#serve_component_content", as: 'component_asset_serve'

  # Serve uploaded client_application asset content
  get 'client_application_asset_serve/:id', to: "asset#serve_client_application_asset_content", as: 'client_application_asset_serve'

  # Asset Pipeline for frontend preview
  get "#{YavuSettings.assets.prefix}/:identifier/*path",  to: ClientApplicationSprocketsController, via: :all, format: false
  get "#{YavuSettings.assets.prefix_preview}/:identifier/*path",  to: ClientApplicationSprocketsPreviewController, via: :all, format: false

  # Frontend clients management
  get 'frontend_servers', to: "frontend_servers#index"
  post 'frontend_servers/:id/:client_application_id', to: "frontend_servers#configure", as: 'configure_frontend_server'
  put 'frontend_servers/:id', to: "frontend_servers#restart", as: 'restart_frontend_server'

  resources :media do
    collection do
      get 'search'
      get 'autocomplete'
      # Type-specific new object routes
      get 'new_audio'
      get 'new_embedded'
      get 'new_file'
      get 'new_image'
    end

    member do
      get 'find'
    end
  end

  resources :extra_attributes, except: [:show]

  resources :settings, only: [:index] do
    collection do
      get 'edit_all'
      put 'update_all'
    end
  end

  resources :shortcuts, except: [:show, :index] do
    collection do
      get 'manage'
    end

    member do
      put 'remove_from_menu'
      put 'add_to_menu'
    end
  end

  resources :articles do
    member do
      get 'copy'
      get 'media', to: 'articles#media_by_article'
    end

    collection do
      get 'most_commented'
      get 'most_read'
      post 'create_copy'
      get 'search',  as: :search
      get 'search_by_section_and_edition', as: :search_by_section_and_edition
    end
  end

  resources :supplements do
    member do
      post 'become_default'
      get 'sections'
      get 'editions'
      get 'active_edition'
    end
  end

  resources :news_sources do
  end

  resources :sections do
    collection do
      get 'tree'
      get 'search',  as: :search
    end

    member do
      get 'articles'
    end
  end

  resources :tags do
    member do
      get 'combine'
      post 'combine_update'
      post 'blacklist'
      post 'unblacklist'
    end

    collection do
      post 'separate'
      get  'search', as: :search
    end
  end

  resources :editions do
    member do
      put 'become_active'
      get 'articles'
    end

    collection do
      get 'search',  as: :search
    end
  end

  resources :client_applications do
    member do
      get  'preview'
      get  'invalidate_routes'
      get  'extra_attributes'
      get  'update_preview'
      post 'enable'
      post 'disable'
      get  'copy'
      post 'create_copy'
      post 'compile_assets'
      post 'notify_clients'
      post 'invalidate_routes', to: 'client_applications#purge_routes'
      patch 'extra_attributes', to: 'client_applications#manage_extra_attributes'
    end

    collection do
      get 'search',  as: :search
    end

    resources :client_application_assets, as: :assets, path: 'assets' do
      member do
        get 'dissasociate_representations'
        get 'edit_content'
        get 'rename'
        post 'toggle_as'
        patch 'update_name'
        patch 'update_content'
      end
      collection do
        get  'new_empty'
        post 'create_empty'
      end
    end

    resources :routes, as: :routes

    resources :representations, as: :representations do
      member do
        get    'rename'
        get    'cover', to: 'covers#edit'
        patch  'update_cover', to: 'covers#update'
        patch  'update_name'
        get    'copy'
        post   'create_copy'
        delete 'discard_draft'
        get    'preview'
        post   'apply'
        get    'manage_assets'
      end

      resources :base_representations_views, as: :views, path: 'views' do
        member do
          post 'associate'
          post 'disassociate'
        end
      end

      resources :representation_assets, as: :assets, path: 'assets', only: [:index, :show, :edit, :new] do
        collection do
          patch 'batch_action'
          get   'new_empty'
        end
        member do
          get   'rename'
          get   'edit_content'
          post  'toggle_into_representation'
          post  'toggle_as_favicon'
        end
      end

      resources :backups, only: [:index, :show, :destroy] do
        member do
          post 'restore'
        end
      end
    end

    resources :newsletters, as: :newsletters do
      member do
        post 'enable'
        post 'disable'
        get  'sendmail'
      end
    end
  end

  resources :galleries do
    collection do
      get 'new_media'
      get 'search'
    end
  end

  resources :users
  resources :roles
  get 'profile', to: 'users#profile'
  patch 'profile', to: 'users#update_profile'

  resources :components do
    member do
      get  'copy'
      post 'create_copy'
      get  'configuration_form'
      get  'enable'
      get  'disable'
    end

    collection do
      get 'search',  as: :search
    end

    resources :services, controller: 'component_services'

    resources :views, controller: 'component_views' do
      member do
        post :make_default
      end
    end

    resources :component_translations, path: 'translations', as: :translations

    resources :component_assets, as: :assets, path: 'assets' do
      member do
        get 'edit_content'
        get 'rename'
        patch 'update_name'
        patch 'update_content'
      end

      collection do
        get   'new_empty'
        post  'create_empty'
      end
    end
  end

  get 'auditing', to: 'versions#index', as: 'auditing'
  resources :versions, only: [:index, :show, :destroy]
  get 'versions/:id/diff_current', to: 'versions#diff_current', as: 'diff_current'
  post 'versions/:id/restore', to: 'versions#restore', as: 'restore_version'

  # Sidekiq panel
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Debug/Development routes
  if Rails.env.development?
    get 'debug', to: 'debug#index'
    get 'debug/icons', to: 'debug#icons'
  end
end

app/models/client_application_asset.rb
class ClientApplicationAsset < ActiveRecord::Base
  include Asset
  self.inheritance_column = nil # no STI

  belongs_to :client_application

  has_many :client_application_assets_base_representations
  has_many :base_representations, through: :client_application_assets_base_representations, source: :base_representation
  alias_method :representations, :client_application_assets_base_representations

  mount_uploader :file, ClientApplicationAssetUploader

  validates_presence_of [ :client_application, :type, :file ]
  validates_length_of %i[type prefix_path content_type], maximum: 255

  after_save :update_representation_assets
  after_destroy :update_representation_assets

  before_destroy :check_before_destroy

  # We must check for uniqueness of file with scope [:client_application_id, :type, :prefix_path]
  # manually because carrierwave sets file after saving record, and before commiting changes
  # There is a database unique index, so check if database restriction is applied
  validate :file_uniqueness

  default_scope { order(:file) }

  set_api_resource id: :id,
      type: ->(x) { x.type.to_s},
      file: ->(x) { x.relative_url }

  def self.toggables
    %w(favicon logo)
  end

  # Methods to manage toggables on client application
  # - Check if it can be toggled.
  # - Check if it is actually set as that
  # - Toggle it
  toggables.each do |toggable|
    define_method("can_be_#{toggable}?") { type == 'image' }
    define_method("#{toggable}_for?") do |container, strict: false|
      container.send("#{toggable}", strict: strict) == self
    end
    define_method("toggle_as_#{toggable}") do |container|
      return false unless send("can_be_#{toggable}?")
      container.send("#{toggable}=", send("#{toggable}_for?", container) ? nil : self)
      container.save!
    end
  end

  def prefix_path=(value)
    old_path = file.current_path
    self[:prefix_path] = value
    if persisted? && prefix_path_changed?
      self.file = File.open(old_path)
    end
  end

  # Complete path to this asset's dir.
  # e.g. data/clients/client_app_identifier/assets/asset_type/
  # Used by rename method on asset's concern.
  def absolute_url
    "#{ClientApplicationAssetUploader.absolute_prefix_for_type(client_application, type)}"
  end

  def copy(client_app = nil)
    client_app.assets.build file: File.open(file.current_path, 'r'), client_application: client_app
  end

  private

    def file_uniqueness
      if ClientApplicationAsset.where('client_application_id = ? and type = ? and file = ? and prefix_path= ?',
                                      client_application_id, type, file.filename, prefix_path).any?
        errors.add(:file,I18n.t('errors.messages.taken'))
      end
    end

    # ClientApplicationAsset can be destroyed if there are no
    # representations associated
    def check_before_destroy
      base_representations.empty?
    end

    def assets_configuration
      client_application.assets_configuration if client_application
    end

    def update_representation_assets
      client_application.representations.each {|r| r.update_assets! }
    end

end

app/controllers/client_application_assets_controller.rb
class ClientApplicationAssetsController < ApplicationController
  load_and_authorize_resource :client_application
  load_resource :asset, :parent => false, :through => :client_application, new: [:new_empty, :create_empty]

  # The following two filters are needed to implement go_back path
  before_action :set_paths_to_client_application_assets_controller, only: [:new_empty, :show, :edit, :new, :rename, :edit_content]
  before_action :set_paths_from_session
  before_action :check_editable?, only: [:edit_content, :update_content]

  def index
    @application_assets = @client_application.assets.page(params[:page]).per(per_page)
  end

  def new
  end

  def new_empty
  end

  def create
    # After creation we MUST redirect to list because of go back shared implementation
    if @asset.save
      redirect_to @list_path, notice: t('client_application_assets.new.messages.success')
    else
      render action: "new"
    end
  end

  def create_empty
    # Creates a new empty asset for this client application allowing to write it
    # in the future.
    @asset.prefix_path = params[:client_application_asset][:prefix_path] if params[:client_application_asset][:prefix_path]
    @asset.file = File.open("#{Dir.tmpdir}/#{params[:client_application_asset][:file]}.#{params[:client_application_asset][:type]}", "w")
    @asset.client_application = @client_application
    if @asset.save
      redirect_to @list_path, notice: t('client_application_assets.new.messages.success')
    else
      render action: 'new_empty'
    end
  end

  def edit; end
  def edit_content; end
  def rename; end

  def show
    @container = @client_application
  end

  def update
    if @asset.update(asset_params)
      redirect_to @show_path, notice: I18n.t('client_application_assets.edit.messages.success')
    else
      render action: 'edit'
    end
  end

  def update_content
    #This action wont fail
    @asset.update_content! asset_content_params[:content]
    redirect_to @show_path, notice: I18n.t('client_application_assets.edit_content.messages.success')
  end

  def update_name
    if @asset.rename(params[:client_application_asset][:file])
      redirect_to @show_path
    else
      render action: 'rename'
    end
  end

  def destroy
    if @asset.destroy
      redirect_to client_application_assets_path(@client_application),
        notice: t('client_application_assets.destroy.messages.success')
    else
      redirect_to client_application_assets_path(@client_application),
        alert:  t('client_application_assets.destroy.messages.has_representations')
    end
  end

  def dissasociate_representations
    @asset.base_representations = []
    @asset.save!
    redirect_to client_application_assets_path(@client_application),
      notice: t('client_application_assets.dissasociate_representations.messages.success')
  end

  def toggle_as
    # Toggles this asset as logo or favicon for current client application
    toggable = params[:toggable]
    return unless ["favicon", "logo"].include? toggable
    msg = if @asset.send("toggle_as_#{toggable}", @client_application)
      status = @asset.send("#{toggable}_for?", @client_application)? 'set' : 'unset'
      {notice: t("client_application_assets.#{status}_as_#{toggable}.messages.success")}
    else
      {alert: t("client_application_assets.set_as_#{toggable}.messages.error")}
    end
    redirect_to client_application_assets_path(@client_application), msg
  end

  private

  def set_client_application
    @client_application = ClientApplication.find(params[:client_application_id])
  end

  def asset_params
    params.require(:client_application_asset).permit(:file, :prefix_path, :toggable)
  end

  def asset_content_params
    params.require(:client_application_asset).permit(:content)
  end

  def set_paths_to_client_application_assets_controller
    if @client_application
      session['client_application_asset.list_path'] = client_application_assets_path(@client_application)
      if @asset.id
        session['client_application_asset.edit_path'] = edit_client_application_asset_path(@client_application, @asset)
        session['client_application_asset.edit_content_path'] = edit_content_client_application_asset_path(@client_application, @asset)
        session['client_application_asset.rename_path'] = rename_client_application_asset_path(@client_application, @asset)
        session['client_application_asset.show_path'] = client_application_asset_path(@client_application, @asset)
      end
    end
  end

  def set_paths_from_session
    @list_path         = session['client_application_asset.list_path'] || client_application_assets_path(@client_application)
    @edit_path         = session['client_application_asset.edit_path'] ||
      @asset && @asset.persisted? && edit_client_application_asset_path(@client_application, @asset) ||
      client_application_assets_path(@client_application)
    @edit_content_path = session['client_application_asset.edit_content_path'] ||
      @asset && @asset.persisted? && edit_content_client_application_asset_path(@client_application, @asset) ||
      client_application_assets_path(@client_application)
    @show_path         = session['client_application_asset.show_path'] ||
      @asset && @asset.persisted? && client_application_asset_path(@client_application, @asset) ||
      client_application_assets_path(@client_application)
    @rename_path       = session['client_application_asset.rename_path'] ||
      @asset && @asset.persisted? && rename_client_application_asset_path(@client_application, @asset) ||
      client_application_assets_path(@client_application)
  end

    def check_editable?
      unless @asset.editable?
        redirect_to @show_path,
                    alert: I18n.t('client_application_assets.edit_content.messages.error')
      end
    end
end

app/helpers/client_application_assets_helper.rb
module ClientApplicationAssetsHelper
  def representations_which_is_present(asset)
    asset.representations.any? ? asset.representations.map(&:to_s).join(', ') : '-'
  end
end

app/views/client_application_assets/_form.html.erb
<div class="form-container">
  <%= form_for [@client_application, @asset], url: (@asset.new_record? ? client_application_assets_path(@client_application) : client_application_asset_path(@client_application, @asset) ) do |f| %>
    <%= render_form_errors @asset %>
    <div class="field-container panel">
      <div class="form-item">
        <div class="row" id="prefix-path">
          <div class="large-12 columns">
            <%= f.label :prefix_path %>
            <%= f.text_field :prefix_path, data: { plugins: escape_configuration('autocomplete' => { searchUrl: search_components_path, object_method: 'slug' }) }  %>
            <div class="hint">
              <%= t('activerecord.attributes.client_application_asset.prefix_path_description') %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-12 columns">
            <%= f.label :file %>
            <%= f.file_field :file %>
            <% if @asset.file_identifier  %>
              <em class="hint"><%= t('client_application_assets.form.current_file', file: @asset.file_identifier) %></em>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <ul class="form-actions right">
      <li><%= f.submit t('client_application_assets.form.submit'), class: "action button radius success" %></li>
    </ul>
  <% end %>
</div>

app/views/client_application_assets/_form_content.html.erb
<div class="form-container">
  <%= form_for [@client_application, @asset], url: update_content_client_application_asset_path(@client_application, @asset) do |f| %>
    <%= render_form_errors @asset %>

    <div class="field-container panel">
      <div class="form-item" data-item-hidden="<%= @asset.id %>">
        <div class="row">
          <div class="large 12-columns">
            <%= f.label :content %>
            <%= f.text_area :content, data: {plugins: escape_configuration('codemirror' => {mode: @asset.content_type})}, id: "codemirror_#{@asset.id}", class: 'codemirror' %>
          </div>
        </div>
      </div>
    </div>

    <ul class="form-actions right">
      <li><%= f.submit t('client_application_assets.form.submit'), class: 'action button radius success' %></li>
    </ul>
  <% end %>
</div>

app/views/client_application_assets/_form_new_empty.html.erb
<div class="form-container">
  <%= form_for @asset, url: create_empty_client_application_assets_path(@client_application) do |f| %>
    <%= render_form_errors @asset %>

    <div class="field-container panel">
      <div class="row" id="prefix-path">
        <div class="large-6 columns">
          <%= f.label :prefix_path %>
          <span data-tooltip class="has-tip tip-right" title="<%= t('activerecord.attributes.client_application_asset.prefix_path_description') %>">?</span>
          <%= f.text_field :prefix_path, data: { plugins: escape_configuration('autocomplete' => { searchUrl: search_components_path, object_method: 'slug' }) }  %>
        </div>
      </div>
      <div class="row">
        <div class="large-6 columns">
          <%= f.text_field :file %>
        </div>
        <div class="large-2 columns left">
          <%= collection_select2_select(:client_application_asset, :type, AssetUploader.empty_asset_extensions, :to_s, :to_s) %>
        </div>
      </div>
    </div>
    <div class="large 12-columns">
      <ul class="form-actions right">
        <li><%= f.submit class: 'action button radius success' %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/client_application_assets/edit.html.erb
<div class="row crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li><%= link_to t('client_applications.assets.title'), @list_path %></li>
    <li>&nbsp;</li>
  </ul>

  <h1 class="large-12 columns">
    <%= title t('client_application_assets.edit.title') %>
  </h1>
</div>

<%= render_flashes %>

<%= render 'client_application_assets/form' %>

<%= render_context_actions :client_application_assets, left: { back: { url: @list_path } } %>

app/views/client_application_assets/edit_content.html.erb
<div class="row crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li><%= link_to t('client_applications.assets.title'), @list_path %></li>
    <li>&nbsp;</li>
  </ul>

  <h1 class="large-12 columns">
    <%= title t('client_application_assets.edit_content.title') %>
  </h1>
</div>

<%= render_flashes %>

<%= render 'client_application_assets/form_content' %>

<%= render_context_actions :client_application_assets, left: { back: { url: @list_path } } %>

app/views/client_application_assets/index.html.erb
<div class="row crud-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li>&nbsp;</li>
  </ul>
  <h1 class="large-12 columns">
    <a href="#" class="right" id="filters-toggle"></a>
    <%= title t('client_applications.list.assets', client_application: @client_application.name) %>
  </h1>
</div>

<%= render_flashes %>

<%= render_context_actions :client_application_assets, 
  left: { 
    new_empty: { url: new_empty_client_application_assets_path(@client_application), class: 'success' } 
  },
  right: { 
    new: { url: new_client_application_asset_path(@client_application) } 
  },
  target: ClientApplicationAsset
%>

<table class="crud-table">
  <thead>
  <tr>
    <th class="large-8"><%= t('activerecord.attributes.client_application_asset.file') %></th>
    <th class="large-3"><%= t('activerecord.attributes.client_application_asset.is_favicon') %></th>
    <th class="large-1"></th>
  </tr>
  </thead>

  <tbody>
  <% @application_assets.each do |application_asset| %>
    <tr>
      <td>
        <%= application_asset %>
        <% if application_asset.logo_for?(@client_application) %>
          (<%= t('activerecord.attributes.client_application.logo') %>)
        <% end %>
      </td>
      <td><%= render_boolean application_asset.favicon_for?(@client_application) %></td>
      <td>
        <%= render_dropdown_actions application_asset, :client_application_assets,
          {
            show:         { url: client_application_asset_path(@client_application, application_asset, :goto => :cli_assets) },
            edit:         { url: edit_client_application_asset_path(@client_application, application_asset) },
            rename:       { url: rename_client_application_asset_path(@client_application, application_asset) },
            edit_content: 
                          { 
                            url: edit_content_client_application_asset_path(@client_application, application_asset),
                            condition: application_asset.editable?,
                            class: 'success'
                          },
            unset_as_favicon:
                          {
                            url: toggle_as_client_application_asset_path(@client_application, application_asset, :toggable => :favicon),
                            condition: application_asset.can_be_favicon? && application_asset.favicon_for?(@client_application),
                            class: 'alert',
                            method: :post
                          },
            set_as_favicon:
                          {
                            url: toggle_as_client_application_asset_path(@client_application, application_asset, :toggable => :favicon),
                            condition: application_asset.can_be_favicon? && !application_asset.favicon_for?(@client_application),
                            class: 'success',
                            method: :post
                          },
            unset_as_logo:
                          {
                            url: toggle_as_client_application_asset_path(@client_application, application_asset, :toggable => :logo),
                            condition: application_asset.can_be_logo? && application_asset.logo_for?(@client_application),
                            class: 'alert',
                            method: :post
                          },
            set_as_logo:  
                          {
                            url: toggle_as_client_application_asset_path(@client_application, application_asset, :toggable => :logo),
                            condition: application_asset.can_be_logo? && !application_asset.logo_for?(@client_application),
                            class: 'success',
                            method: :post
                          },
            download:     { url: client_application_asset_serve_path(application_asset) },
            dissasociate_representations:
                          {
                            url: dissasociate_representations_client_application_asset_path(@client_application, application_asset), 
                            data: { confirm: t('client_application_assets.dissasociate_representations.messages.confirmation') },
                            class: 'alert'
                          },
            destroy:      { url: client_application_asset_path(@client_application, application_asset) }
          }
        %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="row crud-footer">
  <div class="large-4 columns">
    <%= render 'shared/pagination_resizer' %>
  </div>

  <div class="large-8 columns">
    <%= paginate @application_assets %>
  </div>
</div>

<%= render_context_actions :client_application, left: { back: {url: client_applications_path} } %>

app/views/client_application_assets/new.html.erb
<div class="row crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li><%= link_to t('client_applications.assets.title'), @list_path %></li>
    <li>&nbsp;</li>
  </ul>

  <h1 class="large-12 columns">
    <%= title t('client_applications.new.assets', client_application: @client_application.name) %>
  </h1>
</div>

<%= render_flashes %>

<%= render 'client_application_assets/form' %>

<%= render_context_actions :client_application_assets, left: { back: { url: @list_path } } %>

app/views/client_application_assets/new_empty.html.erb
<h1><%= title t('activerecord.actions.client_application_assets.new_empty_for', client_app: @client_application.name) %></h1>

<%= render_flashes %>

<%= render 'client_application_assets/form_new_empty' %>

<%= render_context_actions :client_application_assets, left: { back: { url: @list_path } } %>

app/views/client_application_assets/rename.html.erb
<div class="row crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li><%= link_to t('client_applications.assets.title'), @list_path %></li>
    <li>&nbsp;</li>
  </ul>

  <h1 class="large-12 columns">
    <%= title t('client_application_assets.rename.title', asset: @asset) %>
  </h1>
</div>

<div class="form-container">
  <%= form_for @asset, url: update_name_client_application_asset_path(@client_application, @asset) do |f| %>
    <%= render_form_errors @asset %>

    <div class="field-container panel">
      <div class="form-item" data-item-hidden="<%= @asset.id %>">
        <div class="row">
          <div class="large-12 columns">
            <%= f.label :file %>
            <%= f.text_field :file, value: @asset.relative_url_without_extension(false) %>
            <div class="hint">
              <%= t('component/assets.name_hint') %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <ul class="form-actions right">
      <li><%= f.submit t('component/assets.form.submit'), class: 'action button radius success' %></li>
    </ul>
  <% end %>
</div>

<%= render_context_actions :client_application_assets, left: { back: { url: @list_path } } %>

app/views/client_application_assets/show.html.erb
<div class="row crud-inner-header">
  <ul class="breadcrumbs">
    <li><%= link_to t('client_applications.label.plural'), client_applications_path %></li>
    <li><%= link_to @client_application.name, @client_application %></li>
    <li><%= link_to t('client_applications.assets.title'), @list_path %></li>
    <li>&nbsp;</li>
  </ul>

  <h1 class="large-12 columns">
    <%= title t('client_application_assets.show.title', asset: @asset) %>
  </h1>
</div>

<%= render_flashes %>

<div class="panel show-field-container">
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.client_application_asset.type' %></div>
    <div class="large-9 columns"><%= @asset.type %></div>
  </div>
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.client_application_asset.file' %></div>
    <div class="large-9 columns"><%= render_value @asset.file_url %></div>
  </div>
  <% if @asset.can_be_favicon? %>
    <div class="row">
      <div class="large-3 columns label-element"><%= t 'activerecord.attributes.client_application_asset.is_favicon' %></div>
      <div class="large-9 columns"><%= render_boolean @asset.favicon_for?(@container, strict: true) %></div>
    </div>
  <% end %>
  <% if @asset.can_be_logo? && @container.can_have_logo? %>
    <div class="row">
      <div class="large-3 columns label-element"><%= t 'activerecord.attributes.client_application_asset.is_logo' %></div>
      <div class="large-9 columns"><%= render_boolean @asset.logo_for?(@container) %></div>
    </div>
  <% end %>
  <div class="row">
    <div class="large-3 columns label-element"><%= t 'activerecord.attributes.client_application_asset.content' %></div>
    <div class="large-9 columns">
      <%= render_asset @asset %>
    </div>
  </div>
  <% if @asset.editable? %>
    <div class="row">
      <div class="large-3 columns label-element"><%= t 'activerecord.attributes.component_asset.compiled_content' %></div>
      <div class="large-9 columns">
        <%= render_asset @asset, compiled: true %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="large-3 columns label-element"><%= t('activerecord.attributes.client_application_asset.representations_present') %></div>
    <ul class="large-9 columns no-bullet">
      <% @asset.representations.each do |representation| %>
        <li><%= representation %></li>
      <% end %>
    </ul>
  </div>
</div>

<%= render_context_actions :client_application_assets, 
  left: { 
    back: { url: @list_path } 
  },
  right: { 
    edit: { url: @edit_path },
    edit_content: { url: @edit_content_path, class: 'success', condition: @asset.editable? }
  },
  target: @asset %>